# Generated by Django 5.1.2 on 2025-04-25 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='option',
        ),
    ]
